- _articles/encryption-bug.md
- _articles/upgrade.md
- _articles/windows-drivers.md
Their official branding is `NVIDIA` and that's how it is used across all of system76.com
> Change nVidia to NVIDIA

- _articles/desktop-environment.md
This changes the name "Mint Linux" to the (correct) "Linux Mint" (see [discussion on the Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?f=60&p=1376867#p1376867)).
Cheers!
> Change "Mint Linux" to "Linux Mint"

- _articles/cuda.md
- Append apt source entry to `sources.list`, not `source.list`
- Remove `/` between bionic and main, because apt complains
- Specify `arch=amd64`; not sure if that'll work for everyone, but was necessary for me on a 2018 Bonobo
Unrelated question: should the `apt.pop-os.org` domain be served over HTTPS?
> Fix typo in Ubuntu cuda install instructions

- _articles/upgrade-pop.md
Hello! I considered doing this as an issue, but this seemed easy enough. I'm going through the release upgrade process, and I ran into an unmet dep for `pop-desktop`. It's a simple fix to install the missing package, but this might be something you want your package to include when it is installed (I don't really know how apt packages trigger sub-dep installs).
So far this is the only deviation I've encountered from the upgrade docs. Thank you!
> fix(upgrade): add note about `pop-desktop` missing dep

- _articles/battery.md
The original article wasn't very clear as to what flexicharger actually does. This setting is extremely handy, and unique to system76/Clevo in my experience. Power users looking for desktop replacements surely wish for something like this, but may be unfamiliar with how it works.
> Updated FlexiCharger article

- _articles/laptop-firmware.md
“you’re laptop firmware” -> “your laptop firmware”
This is just a small simple thing, but it stuck out when I read it.
> Fix typo in laptop-firmware.md

- _articles/cuda.md
I saw that @ericphanson closed their pull request due to inactivity: https://github.com/system76/docs/pull/161
I don't know why we don't have `system76-cudnn-latest` to match `system76-cuda-latest`, but the "latest" section of our article should give the latest version. This PR updates the latest package name to 10.1, and adds 10.0 to the list of older versions.
> Update cuDNN package version

- _articles/boot-menu.md
The article for accessing the BIOS or Boot Menu currently specifies that the Meerkat has a different boot menu key than other desktops, but it fails to mention that the BIOS key is also different.
(I confirmed with Aaron that the Meerkat in our lab, which has F2 as its BIOS key, is using production firmware.)
> Correct BIOS key for Meerkat.

- _articles/install-ubuntu.md
The "How to Restore GRUB" article no longer exists; the current article for both GRUB and systemd-boot is called "Repair the Bootloader." This change replaces the broken link with the current one.
> Update link to bootloader repair article

- _articles/live-disk.md
This change updates the link for the latest version of Ubuntu from 19.04 to 19.10 in the live disk article.
It also removes the unnecessary sentence "just click the link and the download should begin!" because all three of the links point to a download page (not directly to a file.)
Finally, it fixes a run-on sentence earlier in the paragraph.
> Update link for latest Ubuntu version

- _articles/yubikey-login.md
There was a missing equal sign within the line for requiring the YubiKey on login.
> I added a missing equal sign.

- _articles/wireless.md
A little late, but this adds a step to the WiFi troubleshooting page to remove the backport-iwlwifi-dkms package, since we've had a significant volume of support tickets solved by taking that step.
> Add command to remove bad backport-iwlwifi-dkms package

- _articles/use-docking-station.md
Just received my Galago Pro on Wednesday. I successfully connected it both at home and at work to my HP G2 Thunderbolt Docks with 2 1080p monitors, 3 usb ports, and ethernet. All I had to do was authorize the docks in the Pop OS Thunderbolt menu. I assume it relies on the dkms driver but that was already installed. Worked much more seamlessly than I anticipated. I'm extremely pleased.
Issues:
- ~~Occasionally gets finnicky and won't recognize the attached monitors especially when resuming from suspend with the Thunderbolt port plugged in. I tend to just unplug the thunderbolt port when suspending and plug it back in after I've resumed from suspend.~~
- Seemed to have trouble driving more than 3 USB ports. When I added a daisy chained a USB hub & tried to drive my cooling pad's fan in …
> Update docking station page to reflect my experience with the HP G2 Dock on the Galago Pro

- _articles/upgrade-pop.md
Pop 18.04 to 19.10 upgrades are ready and happening. This PR updates the support article to reflect this.
The instructions for upgrading from 18.04 to 19.10 are the exact same as upgrading from 19.04 to 19.10, so no separate section is needed at this time.
> Remove disclaimer about 18.04 to 19.10 not being ready yet.

- _articles/login-loop.md
The "Login Loop" article has become extremely outdated. Among other things, this rewrite contains the following improvements:
- The old article claimed Ctrl-Alt-F1 went to a full-screen terminal and Ctrl-Alt-F7 went to the login screen. The new article correctly reflects that Ctrl-Alt-F1 goes to the login screen, and uses Ctrl-Alt-F5 for the full-screen terminal instead.
- The new article clarifies that your "username" is probably different from the display name on the login screen, and gives some common examples for what your username might be.
- The new article heavily expands the user account-specific portion, including explaining how to test whether the issue is user account-specific by creating a test user, and providing several more configuration dotfiles/directories to move out of …
> Update login loop page

- _articles/install-ubuntu.md
Users cannot install the System76 Driver on Ubuntu 19.10 until an apt preferences file has been manually added. (This is still the case, even after the kernel version change to -7625.) This PR updates the Installing Ubuntu article to include this step, so users can install the System76 Driver on their computers running Ubuntu 19.10.
> Add section about apt pin to Installing Ubuntu article

- _articles/pop-recovery.md
A galp4 customer got confused because our article says he can hold down SPACE or ESC to get into the systemd-boot menu. On products with System76 Open Firmware, ESC will access the firmware menu if it's held down from boot.
This change removes ESC as an option in the Pop Recovery article. This makes the article accurate and easier to follow for System76 Open Firmware users. I am not aware of any time when ESC would work but SPACE would fail for getting in the systemd-boot menu, so this should not negatively affect any other users.
> Remove ESC key from sentence

- _articles/system76-driver.md
Good news: a customer found the instructions for adding the apt pin file in the [Install Ubuntu](https://support.system76.com/articles/install-ubuntu/#apt-preferences-file) article.
Bad news: they reported that it was still difficult to find because they checked the System76 Driver article first.
Solution: let's add this information to the System76 Driver article too, so it's there wherever people look for the information. It does directly pertain to the System76 Driver.
> Add apt pin instructions to System76 Driver article

- _articles/server-setup.md
Currently, the link to the Intel BMC manual in this article is broken.
This PR makes two changes:
- Update the link for the Intel BMC manual (the new link goes to revision 2.9 of the manual, while the dead link used to point to revision 2.8.)
- Add a section about the Ibex Pro GPU, which includes a link to the Gigabyte BMC manual and the default username and password. The Ibex Pro's firmware interface is different from our other servers, so this information is critical when setting up an Ibex Pro system.
> Update server setup

- _articles/pop-basics.md
Previously, the Pop Basics article's image descriptions were all just "Pop Desktop." This changes the image descriptions so they actually describe what the image shows, in case someone's using a screen reader or an image fails to load.
> Populate the image descriptions with meaningful descriptions

- _articles/service-manuals.md
This is the first PDF of the Thelio b1 service manual that goes over the following items:
- Taking the top case off and placing it back on
- Replace RAM
- Replace Drives
- Replace Thermal Compound
- Specs of the hardware
> init upload of the first thelio-b1 service manual

- _articles/service-manuals.md
This adds the directory for the R1 in the Thelio directory and a link to the R1 service manual.
> add Thelio R1 service manual and link to it

- .github/workflows/ci.yml
- .gitignore
- Gemfile
- _config.yml
- _layouts/article.html
- css/main.scss
NOTE: DO NOT MAKE CHANGES TO THE `gh-pages` BRANCH
With the addition of the jekyll-last-modified-at plugin, we are no longer able to
rely upon Github to build the site from the `gh-pages` branch because the plugin is
not whitelisted.
Moving forward, please merge changes to the `master` branch which will trigger a build that deploys into the 'public' branch which I've configured as the new Github Pages source. 
+ added jekyll-last-modified-at plugin to project
+ added timestamp to bottom of all articles denoting when the last update was made.
+ added Github Actions for building Jekyll, then pushing the build to `public` branch
+ changed default repo from `gh-pages` to `master` on Github
> Adding timestamp to articles

- _articles/package-manager.md
#187 was closed (not merged.) That PR did remove a lot of information, and it looks like it may have also clobbered the password article. However, this particular commit fixes a typo in the first sentence of an article, so I think we should at least merge this one.
> Apply grammar fixes

- _includes/header.html
The "Edit on GitHub" button currently links to gh-pages, which shows a 404. This will update the edit button to point to master.
> Change gh-pages to master in edit link

- _config.yml
- _includes/header.html
In addition to changing link I also took the opportunity to exclude some of the meta data from Jekyll/Ruby.
> Changed contribute link in header include to point at edit page

- _articles/hidpi-multi-monitor.md
This does the following:
- Removes Ubuntu 16.04 steps as we don't have packages for that release any longer.
- Informals users that those commands will work on both 18.04 releases of Pop/Ubuntu as well as 19.10 release.﻿
> Update HiDPI article

- .github/workflows/ci.yml
- split out the build and deploy parts of CI, so we can check if there is a syntax error in one of the files before deploying
- also uses the same action I use for all the Vue doc pages for deploying, so I know it works
- uses the official docker image for building the docs so it's always up to date
- hopefully more debugging and verbose error messages if something goes wrong
> split build and deploy steps

- _articles/service-manuals.md
This commit adds the lemp9 service manual from the tech-docs website. This is a simple print file output from the site for now.
> add lemp9 service manual pdf

- _articles/system76-driver.md
This moves the apt preferences instructions to the top of the article.
> move apt preferences

- _articles/roadmap.md
Fixed from https://support.system76.com/docs/pop-os-development-approach/
to https://support.system76.com/articles/pop-os-development-approach/
at line 21.
Fixed this issue: https://github.com/system76/docs/issues/378
Waiting for verification.
> Fixed a link.

- _articles/desktop-environment.md
3rd paragraph in (after the `sudo` excerpts) has a typo (see title). This change amends that typo.
> Fixed typo: "enviroment" -> "environment"

- _articles/install-in-vm.md
Pop needs at least 15GB but we recommend 20GB and this fixes a typo.
> Fix VM article

- _articles/service-manuals.md
Adds a link to the Service Manuals article for the Gazelle 15 tech docs.
> Add link to gaze15 tech docs

- _articles/use-docking-station.md
This PR adds a disclaimer for the Pluggable dock that we recommend pointing out that video output on the Gazelle 15 requires GTX 1660 Ti graphics (since the 1650/1650 Ti version does not support DisplayPort over USB-C.)
Since we now have three disclaimers, I changed the asterisks to superscripted numbers instead to make them easier to follow.
Also fixed a couple of small typos that have been pointed out to us previously.
> Add gaze15 disclaimer for Pluggable dock and fix typos

- _articles/install-in-vm.md
Adding a clarification for this should help those - such as myself - who were initially lost for solutions when installing Pop in a VM, due to the inability to change the screen resolution directly from VirtualBox without Guest Additions installed.
> VirtualBox default resolution sometimes cannot fit installer

- _articles/graphics-switch-pop.md
- _articles/graphics-switch-ubuntu.md
Introduce a new "compute" mode that performs all rendering on the
integrated graphics, but makes the dGPU available on the bus (with the
NVIDIA drivers loaded) as a compute node.
Ref: pop-os/system76-power#162
> Add "compute" graphics mode

- _articles/add-a-printer-pop.md
- _articles/add-a-printer-ubuntu.md
https://github.com/system76/docs/pull/424 was merged prematurely and the current command shown (`sudo apt install --reinstall ~n^system-config-printer-`) would cause pop-desktop and gnome-control-center to be removed (because a trailing minus sign tells apt to remove packages matching that pattern if they're installed, and those packages are required by pop-desktop.)
This fixes the command by removing the hyphen at the end, which means those packages will be reinstalled instead of removed, which was the intention of the article before the previous PR.
> Remove trailing dash from package names

- _articles/system-firmware.md
- _articles/transition-firmware.md
I also escaped some instances of Pop!_OS that were not markdown escaped. Some parsers care, others don't.
> Separate transition to open firmware and firmware update articles

- _articles/switch-from-macos-to-popos.md
Changed avaiable top available in the Development section under macOS, - Xcode.
> Fixed typo.

- _articles/bootloader.md
- _articles/pop-20.10-upgrade-help.md
- _articles/pop-recovery.md
This affects any articles where we have the following command:
sudo cp /etc/resolv.conf /mnt/etc/
If we change it to:
sudo cp -n /etc/resolv.conf /mnt/etc/
then customers won't get an error message and possibly freak out
I've found this in the following but might be in more areas.
https://support.system76.com/articles/bootloader/
https://support.system76.com/articles/pop-recovery/
> replace commands

- _articles/use-docking-station.md
I'm using a ThinkPad Thunderbolt Workstation Dock Gen 2 (40ANY230CH) with a Galago Pro `galp5`.
Peripherals connected to the Dock:
* Dell 4K 24" monitor using DisplayPort. At work I tried the same dock with a Samsung 27" 4K monitor.
* Logitec USB receiver for a wireless MX Anywhere 2S mouse
* Wired USB Keyboard (Leopold FC660C)
* Ethernet
* Headphone using the 3.5mm Headphone Jack
No additional drivers were needed, everything just worked.
Only problem so far: The Galago Pro doesn't charge through the dock. [Link to related issue](https://github.com/system76/firmware-open/issues/144)
> Added ThinkPad Thunderbolt 3 Workstation Dock Gen 2

- _articles/keyboard-shortcuts.md
Adding a note for executing shell script via custom shortcut.
Since other distro like Linux Mint has an option to browse to the script and handle by itself, in PopOS we only have command, so a note will help future users.
> Add note for executing shell script

- _articles/use-docking-station.md
I use the Dell WD19 daily at work and the Plugable ud-ultcdl at home with great success. I'm using this with a brand new Gazelle (gaze15) laptop. Note: Just as it states on System76's website to use docks with this laptop you must have the GTX 1660 Ti.
I run the WD19 with three monitors plus the built in laptop display for a total of 4 displays. I so far have only tested the Plugable at home with a single monitor.
Power delivery does NOT work for either of these docks for the Gaze15 (I don't think the Gazelle can even charge via type-c but I may be wrong). My solution is just to leave an extra triple prong power cable for my laptop's power brick plugged in and ready to go next to where my laptop sits on my desk.
There are a couple issues with the WD19 (nothing a show stopper though):
- …
> Add Dell WD19 and Plugable ud-ultcdl dock info

- _articles/use-docking-station.md
Lenevo ThinkPad usb 3.0 Pro Dock works fine with my Lemur. DisplayLink driver required.
Tested with:
- Philips 24" screen via DisplayPort
- HP wired USB Keyboard
- Minicute Ezmouse5 wireless mouse 
- Headphone using the 3.5mm Headphone Jack
Not tested:
- Ethernet
- Screen via DVI
> Include test new Lenovo docking station

- _articles/use-tensorman.md
Tensorman is supported in the two currently-maintained releases, 20.04 LTS and 20.10. There is no longer a need to specify that it was new in version 19.10 (and it's confused some users in Mattermost, who read that sentence to mean it's not supported in newer releases.)
> Remove Pop version numbers from article

- _articles/upgrade-pop.md
I noticed some typos in this article while linking it to someone this morning. This PR fixes the typos and minor grammar issues.
Also, since this section refers to 18.10, 19.04, and 19.10 in the first paragraph, I've made the rest of the section consistently refer to the same set of versions. This includes the `sed` command to replace the old codeword with the new codeword; `disco` would only work for 19.04, we need `cosmic` and `eoan` included in that command since the section is supposed to support 18.10 and 19.10. The new `E` option being added to the sed command [allows](https://unix.stackexchange.com/a/145404) using the `|` or operator so we can cover all three releases with one command instead of three commands.
> Upgrade old releases: fix typos and add more release codewords to sed command

- _articles/backup-files.md
Box.com doesnt have a native client for linux. 
I think you can drop the reference for this app.
> Remove backups apps without linux native support

- _articles/pop-recovery.md
I was copying commands out of this article this morning and noticed there's a `/` in the middle of two command lists. It looks like these were added in https://github.com/system76/docs/pull/512 by mistake (as `/` is not a valid command, it was added to the Pop article but not the Ubuntu article, and that PR didn't say anything about why these lines were added.) The rest of the commands work normally without doing anything at this step.
> Remove stray slash from list of commands

- _articles/nvidia-nvs.md
This PR hides the NVIDIA NVS article as we do not have the hardware any longer to confirm that this setup still works.
> hide article

- _articles/package-manager-pop.md
Closes #493.
This makes a number of improvements to the (already very useful) Fix Package Manager Issues article:
- Adds some Flatpak commands that can clear out [ghost updates](https://github.com/pop-os/shop/issues/198).
- Replaces references to Ubuntu applications and icons with references to the corresponding Pop applications (because the Pop and Ubuntu articles have been split out.)
- Replaces `apt dist-upgrade` with `apt full-upgrade`.
- These two commands are entirely equivalent, but apt's man page lists `full-upgrade` (and does not list `dist-upgrade`), presumably because the new wording is more clear and less likely to confuse users (who can easily confuse a `dist-upgrade` with a release upgrade.)
- Removes unnecessary extra spaces between sentences that Markdown was hiding …
> Add Flatpak commands to Fix Package Manager Issues

- _articles/fix-raw-image-previews.md
This how-to is based on the work done in this issue [pop #1484](https://github.com/pop-os/pop/issues/1484) adding raw image thumbnails to work in 20.04 and 20.10.
> howto on re-enabling raw image previews in nautilus.

- _articles/laptop-battery-thresholds.md
This fixed the link to the Open Firmware System list where it had a .md at the end of the link.
> fixes a broken link

- _articles/switch-from-macos-to-popos.md
Hi System76 folks,
I spotted a very small typo while reading this page: https://support.system76.com/articles/switch-from-macos-to-popos/
I thought I would fix it while I'm at it. 😃
> Fix typo "Text Editer" -> "Text Editor"

- _articles/desktop-environment.md
Closes #419.
The instructions for installing additional desktop environments were re-worked in https://github.com/system76/docs/pull/297, but the troubleshooting information at the bottom of the article wasn't updated at that time. This PR makes the following changes:
- Customize Notification Dialog
- Remove obsolete instructions for restoring the "default" Unity notification dialog. (Xfce doesn't seem to overwrite GNOME's notification dialogs at this time.)
- Fix Broken Desktop Background
- Remove this section, as GNOME Shell now handles the background instead of a separate plugin (so this gsetting has no effect.)
- Remove Duplicate Options From Login Screen
- Remove references to "duplicates" added by the `lubuntu-desktop` and `xubuntu-desktop` packages, since the article no longer …
> Clean up obsolete desktop environment troubleshooting info

- _articles/pop-keyboard-shortcuts.md
- _articles/ubuntu-keyboard-shortcuts.md
Closes #454.
As the current supported releases of Pop!_OS are 20.04 LTS and 20.10, and the current keyboard shortcut scheme is no longer new, the notes and entire sections referring to older versions of Pop are no longer needed (and have started creating confusion, in at least #454 and https://github.com/system76/docs/issues/396.) This PR removes all shortcuts that no longer work in the current releases, and moves the remaining shortcuts into more appropriate categories where possible.
> Remove obsolete keyboard shortcuts

- _articles/upgrade-pop.md
Is there a small error in the update article?
The folder created using mkdir in step 2 for backups was named /etc/apt/backup
In step 4 it refers to a folder named /etc/apt/sources.list.d/backup
> Small suggested changes in upgrading article

- _articles/pop-shell.md
Both Ubuntu and debian use node-typescript
Reference
- https://packages.ubuntu.com/focal/node-typescript
- https://packages.debian.org/buster/node-typescript
> Correct package name of typescript

- Gemfile
This should enable the `redirect_from` blocks found in some of the pages front matter.
> Add jekyll-redirect-from plugin

- _articles/difference-between-pop-ubuntu.md
It seems the link has changed but was not updated in the process. I think that the link leading to "This Week in Pop!" should also be updated or removed since this doesn't seem to be active anymore.
> Update dead link for Pop!_OS's Roadmap article

- _articles/live-disk.md
Updated the link to the Ubuntu 20.04 download, as the original link would load a download page, which would then redirect into a 404.
This new link goes to the download page, then presents the user with the download of the ISO file.
> Update Ubuntu 20.04 Download Link to Fix 404 Error

- _articles/system76-driver.md
Added commands for installing the system76-driver on Fedora, using the community-maintained repository [here](https://copr.fedorainfracloud.org/coprs/szydell/system76/)
Will add full instructions on installing all system76 packages in a different article.
> Add Fedora commands

- _articles/system76-driver.md
- _articles/system76-software.md
This adds a new article for installing our software on Fedora and Arch, it also updates the System76 Driver article to install the firmware daemon before the System76 Driver.
> Update system76 driver arch

- _articles/system76-software.md
This allows the keyboard backlights to be controlled on Fedora on our systems.
> add dkms enable command for Fedora

- _articles/steam.md
Created directions on using `protonup` to installer newer GloriousEggroll forks of proton.
> Add protonup

- _articles/boot-menu.md
Fixes a presumed bad merge seen here, https://github.com/system76/docs/commit/76c7d25038fc4811176fa1a7be7c0153559e67ff#diff-e149dc08caa08c4dbae5b8a8ea32f218ca9108efee651ba5f80b7364d8394c58
https://support.system76.com/articles/boot-menu/
> fix table in boot-menu article

- content/before-you-open-a-support-ticket.md
- content/bluetooth.md
- content/cuda.md
- content/difference-between-pop-ubuntu.md
- content/disaster-recovery.md
- content/dual-booting.md
- content/hardware-failure.md
- content/install-tensorflow.md
- content/open-firmware-smmstore.md
- content/pop-recovery.md
- content/power-on-failure-desktop.md
- content/power-on-failure-laptop.md
- content/switch-from-macos-to-popos.md
- content/use-docking-station.md
Please stop linking to things with `https://github.com/system76/docs/blob/gh-pages` and `https://github.com/system76/docs/raw/gh-pages`. All of those files are served with the website, you can just do `/pdfs` or `/files/firmware` instead.
> fix absolute urls in content files

- modules/link-fixes.js
- nuxt.config.js
This should fix the absolute links not working for static file assets.
> fix absolute path markdown links for static files

- content/steam.md
On Pop/Ubuntu, `$HOME/.local/bin` is not added to `$PATH` unless the directory exists. Sourcing `$HOME/.profile` will add the folder to `$PATH` for the current session.
> Added updating PATH command to the article so protonup is available

- package.json
Nuxt by default will just log errors. We seem to be missing them, so this will just fail CI or Deploy if there is an error logged.
> Fail builds if there is an error during build

- content/tensorman.md
"Jupyter" should be spelled the same way on this line as it is in the command on the next line.
> tensorman: Correct typo

- .github/workflows/ci.yml
- .markdownlint.json
- package-lock.json
- package.json
This PR sets up a markdown linter for all of the article files. This will display nicely for PRs which should make it easier for contributors.
I have disabled some rules like line length, code blocks requiring a language, and white listed some allowed html tags that we use.
Example output for the accessibility article:
```
content/accessibility.md:17 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Accessibility"]
content/accessibility.md:19 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
content/accessibility.md:19:94 MD026/no-trailing-punctuation Trailing punctuation in heading [Punctuation: '.']
content/accessibility.md:25 …
```
> Setup a markdown linter

- content/docking-station.md
Closes #735, updates the version numbers/filenames in the example commands, and makes a couple of small wording improvements for clarity. Also moves the three disclaimers above the DisplayLink section since they apply more to the device lists higher up on the page.
> Update DisplayLink driver information

- content/docking-station.md
Dell Docking Station – USB 3.0 (D3100). Displaylink required.
Test with Pop!_OS 21.04 - Linux Kernel Version 5.11.0-7620-generic
DisplayLink Driver Version 5.4.0-55.153
Tested with : 
* Two Dell 27" Monitors - 2 HDMI connections
* Ethernet Port works
* 3 Front usb ports work fine 
Not Tested: 
* Display port
> Tested Dell Docking Station – USB 3.0 (D3100)

- content/system76-driver.md
To be consistent with other, similar instructions like, https://github.com/system76/docs/blame/master/content/system76-driver.md#L89
> add missing cd command during arch driver install

- content/guides.md
- adds the Launch keyboard to the guides page.
> add launch tech-docs

- content/pop-shell.md
Pop Shell no longer installed by default for Manjaro but according to this is available in the repository:
https://forum.manjaro.org/t/pop-shell-toggle-in-layouts-doesnt-work/68182/5
> update pop shell for Manjaro

- content/live-disk.md
- content/pop-live-disk.md
- Adds the updated table for booting keys from the live-disk article to the pop-live-disk article
- Updated the live-disk and pop-live-disk articles to have a link to the Open Firmware system article
This clears up some confusion with which keys to use to boot to the BIOS and Boot Menu for Open Firmware systems.
> update firmware keys and add a link to the Open Firmware article

- content/docking-station.md
After [updating firmware to latest](https://github.com/system76/firmware-open/commit/14b8a6e967db28596d7108b7a925c60c416d7f45) on my gaze16_3060, I am now able to successfully use the Plugable ud-ultc4k for my needs, which include:
- Connecting two external displays via the DP++ ports on the dock - one display uses a DP -> HDMI adapter and the other uses a DP -> DVI adapter.
_Note: my displays are not pushing 4K resolutions - both max out at 1920 x 1080_
- Connect multiple USB devices (using all of the USB-A ports - haven't tested the USB-C port on front of dock):
- USB headset
- Logitech USB Unifying Receiver
- Logitech USB Webcam
- Connect Ethernet (confirmed link at 1Gbps)
> Updates to include plugable ud-ultc4k

- content/system76-driver.md
- content/system76-software.md
- Updates software steps
- Removes the note about System76 Power GNOME Shell extension not working on GNOME 40 as it does now
- Adds Paru steps
> Update arch software

- content/login-loop-pop.md
- content/login-loop-ubuntu.md
This PR addresses suggestion made in issue: https://github.com/system76/docs/issues/674 
Specifically, it adds notes on backing up/removing xorg.conf as a possible troubleshooting solution for a black screen on login.
Both the Pop and Ubuntu articles have this addition.
Also removed Ubuntu specific instructions from Pop article.
> Update black screen

- content/linux-gaming.md
Since these articles are aimed at users who may be less comfortable with Linux, I think it makes sense to display Pop Shop as the first item, rather than terminal. I think for new users, the terminal is likely more of a fallback option, rather than their primary means of installing software.
This PR was motivated by this comment on Reddit from @mmstick: https://www.reddit.com/r/pop_os/comments/qqa44e/linus_tech_tips_switches_his_personal_pc_to_pop_os/hjz960n/
> Linux Gaming: Prioritize pop shop for installing steam

- content/hardware-failure.md
- content/login-from-live-disk.md
- content/pop-recovery.md
- Creates a standalone article for chroot access.
- This allows instructions for chrooting to be sent to users by themselves, instead of linking to other articles for larger concepts with the chroot nested inside.
- Fixes some minor formatting/typos in the Recovery article.
- Addresses issue: https://github.com/system76/docs/issues/821
> minor typo tweaks recovery, new chroot article

- content/cuda.md
- Removes a `cat` command that pointed to a file that doesn't exit
- Adds a new `cat` command to replace it to check cuDNN version instead
- Adds and removes CUDA/cuDNN versions as they are no longer packaged
- Adds information that certain CUDA/cuDNN versions are only on 20.04 LTS
- Addresses issue https://github.com/system76/docs/issues/765
> Update cuda cudnn

- content/desktop-environment.md
Just a small typo.
`envioronments` -> `environments`
> fix: typo in desktop-environment.md

- content/hardware-failure.md
The `nvme` command referenced by the docs is provided by the `nvme-cli` pacakge:
```
kubuntu@kubuntu:~$ dpkg -S nvme | grep `which nvme`
nvme-cli: /usr/sbin/nvme
```
> Include nvme-cli

- content/upgrade-pop.md
The `system76-dev/stable` PPA is only meant for Ubuntu, not Pop!_OS. In previous versions, having it added wouldn't cause any problems, as it would only provide packages that `system76/pop` also provides; however, now that Impish doesn't use Launchpad anymore, having this file left over can cause confusion.
(Further changes to this article would be needed to show the process to go from e.g. 20.10 to 21.10, but this PPA was not needed even for 20.04, which this section is referencing.)
> Remove Ubuntu PPA from Pop upgrade instructions

- content/pop-incomplete-upgrade.md
Fixes https://github.com/system76/docs/issues/872.
https://github.com/system76/docs/issues/872 was caused by the `https://` protocol missing from the link. This fix also makes the link more specific so it goes directly to the ~upgrade-help channel in the pop-os team, and adds a link to the support website for customers. It also adds a couple of missing commas in this section.
> Replace broken, general link with working, specific link; add missing commas

- content/pop-incomplete-upgrade.md
* added "rm -f" to the sudo rm /etc/apt/sources.list.d/pop-os-ppa.sources to avoid an error the customer might be concerned about
* added sudo in front of systemctl restart pop-upgrade
* added "bash -c "rm -rf" to the empty recovery partition
* added -H to the sudo gedit /etc/fstab
> minor edits

- content/pop-basics.md
Relative link using `articles/manage-repos-pop` lead to the compounded and non-functional link below:
https://support.system76.com/articles/pop-basics/articles/manage-repos-pop
~Replaced the relative link with an absolute link~
Aaron updated and corrected the relative link.
> Fixing broken link

- content/flash-firmware-from-usb.md
This PR adds a dedicated article for preparing and booting a USB in order to flash firmware.
Originally written as a change to the SMMStore, but a dedicated article seemed more appropriate:
https://github.com/system76/docs/pull/890
> Created Flash Firmware From USB Article

- content/tensorman.md
21.10+ has different requirements to install and run tensorman.
> Update for new install instructions.

- content/install-davinci-resolve.md
Using Lite or Studio doesn't work anymore at least for me. What I did try was running this command instead and it worked. ./makeresolvedeb*.sh DaVinci_Resolve_17.4.3_Linux.run
> Specifying the whole DaVinci File name makeresolve

- content/pop-recovery.md
My system broke after latest Nvidia driver updates and while trying to fix the problem realized package manager repair commands link was forwarding to the wrong route.
> route typo fix

- content/transition-firmware.md
Small editing change to correct a typo in description of what is and is not functionally possible in S76 Open Firmware
> fix: Typo in transition-firmware.md

- content/windows.md
The "additional setup" href at the end of both the shared drive and dedicated drive sections is missing the "-not-in-vm" portion of the ID for the relevant section (line 469).
> Fix broken "additional setup" link.

- content/windows.md
Disclaimer was bumped down to the 3rd section, which kind of defeats the purpose of a disclaimer warning about the scope of support.
> Moved the Disclaimer section back to the top

- content/docking-station.md
Docking Station: CableMatters Dual Display USB-C Docking Station, model 107008-BLK.
https://www.cablematters.com/pc-881-127-cable-matters-60-ghz-wireless-docking-station-hybrid-model-with-usb-c.aspx
I use this docking station with my Lemur Pro (lemp10) to connect via DisplayPort to an external monitor (1920 x 1080), a gigabit Ethernet connection, as well as mouse/keyboard input through the USB-2 ports. It also supplies power to the computer (up to 60 W). No issues encountered during first 24 hours of use, and it worked out of the box. I did test the HDMI port initially and that also works. Suspending the laptop then waking from keyboard through the docking station works.
I have not tested data transfer over the USB-3 ports, but the power output on the USB-A port on the front does work.
I …
> User tested CableMatters docking station

- assets/styles/tailwind.css
This PR adds a line to the `tailwind.css` stylesheet to allow the Markdown `#` headers to act as foldable sections.
Without the changes here, the folding `>` icon appears a line above the header's text.
> Added line to tailwind.css for foldable headers.

- content/linux-gaming.md
The old URL no longer works, so replaced it with the new one.
> Replaced GameHub's URL

- content/install-davinci-resolve.md
The name of this package has changed in 22.04 LTS.
> Update libssl package name for DaVinci Resolve installation

- content/software-triage.md
The link from `software-triage` to `manage-repos-pop` was broken, as it had an `.md` extension in the URL. Broken link was reported by a customer.
> fixing broken link to `manage-repos-pop`

- content/bluetooth.md
- package-lock.json
Some of the instructions on this document no longer apply for Pop!OS v22.04, so I've split up those commands into a version for v22.04 and a verison for previous releases. I also added a note to the section about the `module-bluetooth-discover` Pulseaudio module, which is no longer used in v22.04.
> Update Bluetooth troubleshooting commands for v22.04

- content/audio.md
expand section to clear current saved settings for PulseAudio and Wireplumber
> Add commands to clear wireplumber saved settings

- content/open-firmware-systems.md
This adds these models to the list of Open Firmware and Open EC per @crawfxrd .
> Add oryp9, lemp11, darp8, and gaze17

- content/system76-driver.md
- content/system76-software.md
- Updates the steps for adding system76-driver and other software
- Moves sections between articles as the driver depends on the system76-firmware package now 
- Adds section to add Jeremy's public key to build our software as it seems to be needed currently
> Update Arch sections

- package-lock.json
- package.json
This update to the components library will remove the Telegram link from the footer.
> Update components to release 1.4

- content/audio.md
- content/serval-dac.md
Closes #1044.
Adds the new instructions for PipeWire, but keeps the old ones for PulseAudio around for reference.
The new PipeWire instructions have been confirmed by several users in Mattermost, and I've also tested it myself on my serw10.
> feat: Update DAC crackling instructions for PipeWire

- content/docking-station.md
It does not natively support multiple monitors with the Lemur. I tested this myself and when it didn't work, I confirmed this with Pluggable's  support.
Apologies for not linking to the PR number, but I don't know what the number will be before the PR is made.
> Update for Plugable UD-ULTC4K

- content/before-you-open-a-support-ticket.md
- pages/index.vue
- plugins/font-awesome.js
moves the "before you open...." article into the Contact Us section
> update the contact us section

- content/bootloader.md
UEFI boot verify command's expected output was put in the subsequent section incorrectly. This has been changed to its correct section.
> Verify UEFI boot: Expected output correctly placed

- content/live-disk.md
CertUtil in Windows 7 requires the HashAlgorithm option to be uppercase. In this case, SHA256 needs to be uppercase. In Windows 10, case does not matter. I have not verified with other versions, but I presume that all versions of windows will work with SHA256 specified in uppercase.
> Uppercase Hash Algorithm for CertUtil

- content/system76-software.md
This adds the steps needed for System76 hardware support in NixOS. This does the following:
- Adds system76-power
- Adds system76-firmware
- Adds system76 kernel modules
Documentation:
https://nixos.org/manual/nixos/stable/options.html#opt-hardware.system76.enableAll
> Add NixOS configuration

- content/cuda.md
Recent request from customers on how to get specific versions of CUDA led to adding steps and commands that will get CUDA 12.1 installed as docker image files. 
Spot tested the instructions and both reported CUDA version matches 12.1 but `nvcc` version is present and matches expected version. Building example CUDA projects works
> Docker CUDA updates

- content/kernelstub.md
The `-o` option actually replaces the whole boot options' list passed to the kernel instead of adding to the configuration (if they aren't present already), which is done using `-a` (or the lengthier `--add-options`).
> [FIX] kernelstub: wrong command for adding kernel options

- content/graphics-switch-pop.md
- content/graphics-switch-ubuntu.md
This adds new models to the list with switchable graphics. I wonder if we should just put the models that we started offering switchable graphics since every system in the 13th Gen Intel has a dGPU so it has switchable graphics. Then we would not have to update this page as often.
> Add missing `addw3`, `gaze18`, `oryp11` models

- content/laptop-battery-thresholds.md
I'm not sure if the note needs to be more obvious, but this at least gets the info into this article.
Also corrected two instances of periods inside of parentheses. They should be outside.
Side note: further down, the "Proprietary firmware" section doesn't apply to the Pangolin. I might need to file an issue about that one.
> Add note about new 90% default start threshold

- content/install-minecraft-server.md
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates the old wiki link accordingly.
> Update Minecraft wiki link to new domain

- content/system-firmware.md
The instruction regarding taking a picture or screenshot of the instructions showed up twice. 
I left the later one, as I feel it provided better emphasis to an important point.
> Remove duplicate instruction

- content/before-you-open-a-support-ticket.md
Minor fixes in one paragraph of the Before You Open a Support Ticket page.
> Fix misplaced word and use "back up" (verb) instead of "backup"

- layouts/default.vue
> Update omnibar with link to Tuxmas page

- content/guides.md
Noticed that my model wasn't listed in `guides.md`, but it does have a tech docs page.
> Update guides.md to include Lemur Pro 12 (lemp12) tech doc

- content/pop-recovery.md
By using -R instead of -B, we ensure that the nested mount of /sys/firmware/efi/efivars/ becomes mounted in our target filesystem, which allows us to do various boot repairs with an EFI system.
> Use recursive binding before chroot

- shell.nix
This allows someone to use `nix` to test changes to the docs. This also allows someone to not need to use the NodeJS package or PPA (for a newer version of NodeJS) so less packages/PPAs.
> Add nix-shell file to use nix for testing

- content/launch-keyboard.md
Use "its" (possessive), instead of "it's" (contraction)
> Fix typo in launch-keyboard.md

- content/rocm.md
This adds an article about installing ROCm (to enable HIP and OpenCL). This is AMD's equivalent of installing CUDA.
In the past, this was a messy process that required running an installation script and (depending on the use case) installing DKMS modules, which didn't always work well with the Pop!_OS kernel. However, at this point, AMD has an Ubuntu repository with a ROCm package that works together with the AMDGPU driver built into the kernel.
There may be some proprietary applications that aren't compatible with this form of ROCm yet, but this is the smoothest experience we can currently offer AMD users for enabling GPU compute, and it works with at least some known applications such as Blender and PyTorch. I think it makes sense to publicly document this as being a supported method of …
> Add ROCm article

- content/guides.md
Jenn had trouble finding the lemp13 tech docs today because she didn't know how to get to tech docs without clicking one of the links for a specific model. To help remedy that, I think it would be a good idea to include a general link to tech docs and a mention that newer models may not be listed in the table yet, since they always have to show up there before they can be added here.
(Long-term, it would be nice to figure out a better solution for tech docs discoverability, like the one initially proposed in https://github.com/system76/docs/pull/1145 but in a more fitting spot. And this Markdown table is getting pretty cumbersome to update, so it might be good to figure out a better format for the article here, too.)
> Add recent tech docs models & link to tech docs homepage

- content/system76-software.md
power-profiles-daemon (enabled by default on Gnome NixOS installs) must be disabled for system76-power to start. This PR includes that info in docs.
> Add note about need to disable ppd on NixOS

- content/cuda.md
Cuda 12.2 is deprecated, and display nasty warning.
the driver version 555 is currently 6 day old.
the driver version 550 was built on top of cuda 12.4.
> Update cuda.md, replace cuda 12.2 by 12.5

- content/rocm.md
I ran into some permissions issues using Docker Desktop with ROCM and was able to resolve these issues by using docker.io instead and running docker as sudo. You can refer to the comments [here](https://gist.github.com/guilt/6c901f7ac0a726685b6334798da77c00?permalink_comment_id=5131866#gistcomment-5131866) for more information.
I thought it would be good to add a note here so that others can avoid these issues.
> Add info on docker usage to rocm install instructions

- content/bluetooth.md
This adds the suggested btusb reload commands from https://github.com/system76/docs/pull/1217.
This also improves the formatting of the command descriptions and fixes an issue with the ordering of a header marking commands for older Pop!_OS versions.
> bluetooth: Add btusb reload commands (from #1217)

- content/bootloader.md
Implements https://github.com/system76/docs/pull/1204 for the Bootloader article.
Replaces https://github.com/system76/docs/pull/1083/.
I changed all of them instead of just the UEFI sections, since it's one character either way and there's no reason not to do it this way. May also avoid people seeing one and thinking they're the same, since R and B look so similar.
> bootloader: Make bind mounts recursive for EFI vars support

- .github/workflows/deploy.yml
Keeping the history of gh-pages adds a lot of bloat when trying to clone the repository. The force_orphan option added pushes just one commit with no prior history to the gh-pages branch on every change, which should significantly reduce the size of the repository.
> Do not keep gh-pages history

- content/laptop-battery-thresholds.md
- Changes the note to a table about the Pangolin models that do not support either option
- Moves the table to the top about thresholds in general rather than the bottom
- Notes that they do not support Charging Thresholds as well as FlexiCharge
- Adds keywords
> Update battery thresholds article

- content/hardware-failure.md
* Creating files manually in the root filesystem should be avoided if it is not necessary. In the case of these instructions, setting the `CUDAPATH` variable when building gpu-burn suffices as a replacement; furthermore, the APT alternatives system automatically creates a symbolic link that avoids the need to hardcode a specific version number here.
* Explain how to pass a different GCC compiler path to the Makefile for the gpu-burn project, to avoid compilation errors that occur with the version of GCC that is shipped with Pop!_OS 20.04 by default.
> Add tips about getting gpu-burn to compile

- LICENSE.md
Closes #886. Re-adds the license as it was before (with the HTTP link changed to HTTPS).
> Re-add CC BY-SA 4.0 license

- content/live-disk.md
This PR is to add a note about data collection in the recommended Windows imaging tool, balena Etcher.
I was dismayed to find the recommended app Etcher had data collection, and it is on by default. I did not think to check until after I had used it. I think this is important to note for future users. Longer term, a different tool should be recommended because of this.
> note on etcher data collection

- shell.nix
While trying to test https://github.com/system76/docs/pull/1301, I found that a fresh clone of the repo on a system with a fully updated Nix installation (`nix-channel --update`) would no longer work, because Node.js 18 is [end-of-life](https://nodejs.org/en/about/previous-releases) and Nix has removed it from their repo. This updates the package name to use the next LTS release. `npm ci` and `npm start` still work to build the repo after doing this.
This does not affect the live site, only building locally in a Nix shell.
> chore(ci): Bump Nix Shell's Node.js from 18 to 20

- content/install-davinci-resolve.md
- content/pop-cosmic-keyboard-shortcuts.md
`qtwayland5` is also needed on 24.04 with COSMIC. Not required but also available on 22.04, so still don't need to split the list out.
> Add another dependency for DaVinci Resolve installation
