_articles/oem-firstboot.md

adds \<kbd> tags for consistency

adds <kbd> tags to line 38

---

_articles/windows.md

fixes \<kbd> tag to display ALT key image properly.

fixes line 56

---

_articles/restore.md

Fixed typo

---

_articles/audio.md

Issue I had with a new Lemur with the resolution.

add clicking noise fix via pulseaudio config clearing

---

_articles/cjdns.md

Page was not rendering properly due to indentation and markdown syntax issues.

Fix md rendering

---

_articles/ubiquity-bug.md

On the note about the link to OEM Firstboot, is that a link to a future article or just left over from something else?

rephrased second paragraph's second sentence a bit for clarity.

---

_articles/laptop-firmware.md

short url will point to this article

Add laptop firmware instructions

---

_articles/hardware-failure.md

mcelog is not in the Ubuntu 18.04 repos

Updated Machine Check Exceptions Section

---

_articles/cuda.md

Update CUDA and cuDNN for our packaged versions.

Cuda latest

---

_articles/advanced-luks.md

how to add more then one LUKS key for FDE.

Advanced luks

---

_articles/hidpi-multi-monitor.md

on how to disable the HiDPI Daemon on 16.04 and 18.04.

Updated HiDPI article

---

_articles/containers.md

Just moved the command lines in the correct places

Sharing command lines were inversed

---

_articles/pop-recovery.md

Just some very minor omissions that I noticed while reading through the article.

Minor grammar fixes

---

_articles/cuda.md

Fixes a small typo on the cuda page

Typo cuNNN -> cuDNN

---

_articles/hardware-failure.md

- Corrected some of the nvme smart-log commands.
- Added mcelog download, compile and install commands
- Linked support to System76 support page

minor command and text changes

---

_articles/install-tensorflow.md

Correct a typo in the line plus add it to its own file to prevent messing up the main list.

Fix Sources file in TENSORFLOW docs

---

_articles/customize-gnome.md

Replace "updates" with "updated", it sounds better.

Customize GNOME - Propose a Correction

---

_articles/battery.md
_articles/desktop-environment.md
_articles/package-manager.md
_articles/server-setup.md
_articles/terminal-basics.md

Hi - wanted to try contributing and so this is my first attempt at that. I just went though the docs to see where we had the incorrect it's and fixed them to the possessive its where appropriate.

Fix it's typos to its

---

_articles/pop-recovery.md

grammar fix. added a few words in pop-recovery.md
Just a few very minor things I came across while browsing the System76 website.
My first very simple contribution to open source :sweat_smile: 
Hope it helps.

fix small typos

---

_articles/bootloader.md

Cleaned up the sets of commands to mount and update the boot-loader

Updates to how mounting and command

---

_articles/install-ubuntu.md

change the last uses of `nomodeset` over to `nouveau.modeset=0`

phase out the use of nomodeset and switch to nouveau.modeset=0

---

_articles/dual-booting.md

Should fix this issue once merged to the Pop page as well:
https://github.com/pop-os/docs/issues/81

Update dual boot

---

_articles/dual-booting.md

Closes Update dual boot #180 wording.

Fix the "it's" with slight edit.

---

_articles/live-disk.md

Update the Ubuntu LTS link from 18.04.2 to 18.04.3 (to fix a broken link.)

Update Ubuntu LTS link to 18.04.3

---

_articles/tensorman.md

Proofread and reviewed by Aaron and I.

Tensorman File Edited for Content

---

_articles/upgrade-pop.md

Add a period at the end of the first sentence. Presentation is important.
Also, clarify that this feature is not ready yet, but will be implemented in November.

Add period, clarify message.

---

_articles/upgrade-pop.md

added required "systemd' to end of the upgrade terminal command.

Fix to incorrect command

---

_articles/boot-menu.md

Fix grammar in the recent PR (235) that was merged without having its reviews resolved.

Correct grammar in boot menu article

---

_articles/graphics-switch-pop.md
_articles/graphics-switch-ubuntu.md

PR #218 was closed because we updated the graphics switching articles before anyone got the chance to review the PR. I did a quick read-through on those two articles for grammar, consistency, and readability.

Improve grammar & clarity in graphics switching articles.

---

_articles/hardware-failure.md

Adding Benchmarking and GPU Burn testing to the hardware failure article.

Update hardware failure

---

_articles/dual-booting.md

Not ready to merge I just want some feedback on what we have so far and what has been changed.

Update dual boot article

---

_includes/footer.html

https://github.com/system76/docs/issues/260
This also corrects the format to follow the main site's better.

fixes issue: 260

---

_articles/use-docking-station.md

of tested systems for the docking station.

add darp6 to the list

---

_articles/serval-dac.md

I keep having to look up these commands in Slack to send to people, and it would be better if they were in an article so people can find it themselves if they want to.

Add article about the Serval's DAC clicking

---

_articles/service-manuals.md

This commit adds opening and closing () to fix a link.

fix broken link

---

_articles/cuda.md

sudo apt install system76-cudnn-10.1 fails so suggest using 10.0

cudnn-10.1 is not availible

---

_articles/cuda.md

This addresses this comment from @mmstick 
https://github.com/system76/docs/pull/250#issuecomment-579989109

fix the version of cudnn

---

_articles/battery.md

Update battery article

---

_articles/use-openvpn.md

This updates the article to follow our writing style better﻿

Update OpenVPN article

---

_articles/encrypt-extra.md

This updates the article content to match our style better﻿

Update article style

---

_articles/pop-keyboard-shortcuts.md
_articles/ubuntu-keyboard-shortcuts.md

Adds a Ubuntu article for shortcuts and renames the Pop one so that they are named differently on the support page.

init commit, tested shortcuts and reworded somethings

---

_articles/desktop-quickstart.md

This adds a missing period in the Set Up User Account section and adds Thelio in the keywords.﻿

Corrects a missing period and adds some tags

---

_articles/system-firmware.md

This update does the following:
- Update the instructions to take into account different firmware OEM.
- Update the instructions to take into account Open Firmware.
- Update the instructions to take into account the customer using USB Type-C to charge their machines.

Update firmware doc

---

_articles/live-disk.md

This updates the link to Ubuntu 18.04 to the 18.04.4 release link.

updates the Ubuntu link to the 18.04.4 release

---

_articles/thelio-power-button.md

"Inststalling" should be "Installing", this affects our ability to link directly to that section.

Correct typo in installing header

---

_articles/webcam.md

Update to be more clear on webcam toggle

be more clear about restarting applications when toggling the webcam

---

_articles/system-firmware.md

It goes over adding the firmware manager for the next boot and rebooting the machine.

add the schedule command for the firmware manager article

---

_articles/upgrade-pop.md

Fixes to the upgrade article while on a call

Updates for upgrading 19.04

---

_articles/dash-to-dock.md
index.html

This renames the article title to avoid confusion with the new launcher in Pop Shell in Pop 20.04.

Rename launcher article

---

_articles/Pop!_OS-20.04-LTS-Release-Notes.md

Fixes the GNOME bullet points and moves Linux kernel out of the GNOME section.

Fix formatting in release notes.

---

.github/workflows/ci.yml

set jekyll for building to 3

---

_articles/Pop!_OS-20.04-LTS-Release-Notes.md
_articles/backup-files.md
_articles/battery.md
_articles/bluetooth.md
_articles/difference-between-pop-ubuntu.md
_articles/system-firmware.md
_articles/upgrade-ubuntu.md

This updates the section to pop so that the article appears to customers.

update description and section

---

_articles/graphics-switch-pop.md
_articles/graphics-switch-ubuntu.md

There was a change that converted intel to integrated in the system76-power package. This update makes that change for the commands and other text in both articles for graphic switching.

Update graphics article

---

_articles/upgrade-pop.md

Added workarounds currently used by support for upgrade issues, removed outdated imagery

Update Pop Upgrade Article

---

_articles/graphics-switch-pop.md
_articles/graphics-switch-ubuntu.md

Added gaze15, addw2 to list of switchable graphics products

Update products that support switchable graphics

---

.gitignore
css/main.scss
index.html

Quick update to the home page with revised copy.
- Updated copy on `index.html`
- Removed erroneous tags towards top of `index.html`
- Added `Gemfile.lock` to `.gitignore`

Updating homepage copy

---

_articles/service-manuals.md

this removes a double Thelio Major in the Tech Docs column and adds the oryp6 to the Tech Docs column.

Updates the table

---

_articles/install-in-vm.md

Small consistency improvement.

Header should be capitalized

---

_articles/battery.md

This let's our customers know that our Open Firmware laptops don't support Flexicharger.

add statement about Open Firmware

---

_articles/system-firmware.md

Just in case they don't think to try it a second time.

Add note about pressing power button more than once

---

_articles/battery.md

System76 Open Firmware has added support for charging thresholds.
Pending release of
- system76/coreboot#15
- pop-os/system76-acpi-dkms#4

battery: Update charging thresholds info

---

_articles/upgrade-pop.md

changed to 20.10 and modified the older releases upgrade section

Update to 20.10 instructions

---

_articles/Pop-20.10-Upgrade-Help
_articles/pop-20.10-upgrade-help.md

confirmed fixes for common 20.10 Pop upgrade issues

Create 2010 upgrade helper article

---

_articles/live-disk.md

Added Open Firmware boot key in chart

---

_articles/upgrade-ubuntu.md

This updates the imagery from Ubuntu 14.04 LTS (upgrading to 16.04 LTS) to 18.04 LTS upgrading to 20.04 LTS. This also updates the Dash to Overview for GNOME Shell and other key terms like Activities. This also adds a screenshot of the Other Software tab in Software & Updates.

updated wording and images

---

_articles/fix-raw-image-previews.md
_articles/open-firmware-systems.md

This adds an open firmware system list to the articles and will be used in the battery thresholds article.

Open firmware system list

---

_articles/dual-booting.md

This adds links to the drivers and reorders the article as well.

Update dual boot drivers

---

_articles/transition-firmware.md

Add note about galp keyboard behavior on Open Firmware

---

_articles/install-pop.md

This addresses this issue:
https://github.com/system76/docs/issues/406

Update Install Pop name

---

_articles/live-disk.md
_articles/pop-live-disk.md

This makes the article easier to find and understand what they are for.

update title and desc of live disk articles

---

index.html

This adds our support hours on our support page (support.system76.com) per Alex on support's feedback.

add support times

---

_articles/switch-from-macos-to-popos.md

1Password now have a fully fledged native client for Linux: https://support.1password.com/getting-started-linux/

Remove Comment on 1Password only Providng Terminal and Browser

---

_articles/before-you-open-a-support-ticket.md
_articles/clear-cache-and-cookies.md
index.html

reorder Support Tickets section

---

_articles/system76-software.md

adding missing system76-software article

---

index.html

This PR adds buttons under each section to move you back to the top of the page where the section buttons are.

Top buttons

---

content/boot-menu.md
content/pop-recovery.md

This PR updates some article tables so that they work in the new backend.

Update and correct tables

---

content/release-schedule.md

This PR adds a link to the Ubuntu release cycle and removes outdated content.

update content on Release page

---

content/install-ubuntu.md

This PR updates the Install Ubuntu article.

update article and images

---

content/login-loop-pop.md

Spelling fix for Finished in the Recovery section.

Spell check on login-loop-pop.md

---

content/network.md

This is a great breakdown, by the way! 🎉

Fix link formatting for networking doc

---

content/use-vpn-software.md

Adjusted spelling from "Graphcial" to "Graphical"

adjust spelling

---

assets/styles/tailwind.css
components/article-listing.vue
nuxt.config.js
pages/index.vue
tailwind.config.js

Updates the homepage with styles from Maria after review:
- update card styles
- update card icons to warm gray circles
- update homepage typography to match article styles

Update homepage styles from Maria

---

content/use-vpn-software.md

Changed "a" to "an" when referring to ovpn files

Minor grammar changes

---

content/ppa-third-party.md

Changed 'Person' to 'Personal' in the long form of PPA

correct PPA long form

---

content/guides.md

- Updates the title for make it easier to find when searching

Update guides manuals 3

---

content/windows-drivers.md

- Adds a link to the Windows drivers for our Open Firmware/Open EC systems

add github link for Open Firmware/Open EC systems

---

content/guides.md

- It reorders the links so that you know where the link is taking you. 
- Updates Guides and Service Manual to a the more generic Documentation wording.

Update the guide page

---

content/minecraft-server-hosting.md

Review my changes, please @jaxsnjohnson

Minecraft server

---

content/clear-cache-and-cookies.md

- Moves the Clear cache and cookies article to software troubleshooting

move article to another slot

---

content/disaster-recovery.md

It's Data Recovery. It's not disaster recovery :) 
The link should be changed as well.

update to remove the word disaster

---

content/desktop-environment.md

it should be /usr/share/xsessions, notice the sessions word has a s.

Fixing a typo

---

content/desktop-environment.md

- Adds a note about changing desktops
- Addresses this issue: https://github.com/system76/docs/issues/783

add note about changing desktops

---

content/windows.md

- Adds oryp8 to Windows article

add oryp8 to Windows article

---

content/hardware-failure.md
content/using-geary.md

Renamed the email article to include the word "email" so it's clearer what the article is about.

Rename "Using Geary" to "Set Up E-Mail"

---

content/setup-face-recognition.md

I ran through this setup this morning and was able to get howdy working. I just wanted to update the doc to include a mention of the need to install ffmpeg. When I originally tried to run ffplay I got an error saying that I should try installing ffmpeg first. Hope it helps, thanks!

Update doc to mention install of ffmpeg

---

content/guides.md

add oryp8 and pang11

---

content/custom-mouse-buttons.md

- Adds Piper and Solaar install instructions.

Update mouse custom article

---

content/backup-files.md

in case apt isn't working, offering a second option for installing deja dup backup

Added how to install deja dup via flatpak

---

content/customize-gnome.md

This pull request contains two fixes to typos I observed in the [Pop!_OS Customization](https://support.system76.com/articles/customize-gnome/) article.  This is my first pull request into System76 repos - please advise on any contribution guidelines.

Fix typos in Pop!_OS Customization page

---

content/upgrade-pop.md

I upgraded from 20.10 lately and these two typos had made it quite a bit harder. (especially the first one)

fixed important typos in code snippets

---

content/hardware-failure.md

Add introductory sentence, and thermal testing text from unexpected-reboots.md

Add CPU thermal information

---

content/active-directory-client.md

I've used this script and i get errors with the double dashes because they're not the same type on the website. I've changed it

Wrong Type of -- for msktutil, this command fails

---

content/system76-software.md

* Add space after period
* Remove and

Fix typos in system76-software.md

---

content/enable-hibernation.md

Ran through commands in 21.10 for hibernation to verify that they continue to work
* expend on security benefit for hibernation over suspend: thanks to @ChristopherRogers1991
* update for clarity on point where you need to reboot
* add  #comments for some of the commands where you edit config files in bash

Updates for 21.10

---

TESTING.md

This adds a `TESTING.md` document with criteria for QA testing within the repo.

Add checklist for QA testing

---

content/graphics-switch-pop.md
content/graphics-switch-ubuntu.md

Add `kudu6` as a Laptop model that has switchable graphics.
Updated releases on both articles at the same time

Update switchable graphics for kudu6

---

content/system-firmware.md
package-lock.json

The plural of the abbreviation "OS" is open to debate, but it's definitely not "OS's", which is a possessive. Changing it to "Updating on Other Operating Systems" which is clearer and obviously correct.

Correcting "Updating on Other OS's" header

---

content/use-amd-fsr.md

Fixes PR #991
Thanks @manuelojeda for bringing this to our attention. I tested your changes live and they work, except the forward slashes needed to be removed from the end of header links for them to go to the correct part of the page.

Apply Fix FSR Changes

---

content/live-disk.md

As the title states.
21.10 -> 22.04
rock on

Update 22.04 iso filename

---

content/enable-hibernation.md

the command at line 79 is missing a single space separating arguments

fix missing space in enable-hibernation.md

---

content/use-amd-fsr.md

We have often been asked how to activate the FSR in Bottles and I believe this is the place, at least for Pop! users.

add FSR instructions for Bottles

---

content/guides.md

- Adds link to the gaze17 tech-docs

Add gaze17 tech-docs

---

content/switch-from-macos-to-popos.md

- Updates the shortcuts for workspaces a bit depending on the version of Pop!_OS.

Updating switching from macOS article

---

content/system76-driver.md

Fedora bits got dropped on the floor. Add them back to the page.

Add back in Fedora COPR repository

---

content/guides.md

- Add lemp11 tech docs
- Add darp8 tech docs

Add lemp11 and darp8 tech docs

---

content/enable-hibernation.md

The security benefits were not further elaborated on and the following sentence makes the statement confusing as it is actually talking about vulnerabilities in hibernation

fix(enable-hibernation): clarify vulnerabilities

---

content/format-drive.md

Updated per feedback in #975 - added sections to explain each option and link to the appropriate articles.

added subheaders for each option and linked to appropriate article

---

content/launch-keyboard.md

Update link to AUR source package, since it was renamed on July 5, 2022

Update link to AUR source package

---

content/package-manager-pop.md
content/package-manager-ubuntu.md

- Add headers to clarify sections
- [removed -m flag](https://github.com/pop-os/docs/pull/15#discussion_r958958351)
- Added descriptions for commands

Update Troubleshooting Package Manager Issues Articles

---

content/open-firmware-systems.md

Added documentation for galp6.

Update open-firmware-systems.md to include galp6

---

layouts/default.vue

Small update for Build Your Beast promotion
- omnibar color + message
- footer color

Update components for Build Your Beast sale

---

.github/workflows/deploy.yml
nuxt.config.js
package-lock.json
package.json

adds the [nuxt-content-git](https://www.npmjs.com/package/nuxt-content-git) module
closes #1100

fix: inaccurate last edited date

---

content/power-on-failure-laptop.md

link to docs was bad link
changed to current link

bad link to docs

---

content/system76-driver.md
content/system76-software.md

fix: paru sync command

---

content/media-production-on-pop.md

I'm not sure why https://github.com/system76/docs/pull/1102 got closed, but I still think it's a good addition. I've recreated it here, with a tweaked description for Krita. 
I also added a few keywords for apps that are listed, but didn't have keywords yet.

Add Krita to media production list

---

.markdownlint.json
content/boot-menu.md

boot-menu: Slightly reformat & add pang12

---

content/launch-keyboard.md

Add Launch Heavy and slight updates around firmware updates.

Add Launch Heavy

---

layouts/default.vue
package-lock.json
package.json

- updates @system76/components to 1.6

Update header with link to launch keyboard

---

content/windows.md

This PR adds laptops and desktops, as well as updating their status

Add models and update text

---

content/launch_2-firmware-update.md

Update launch_2-firmware-update.md

Add note to use launch cables for firmware updates

---

content/difference-between-pop-ubuntu.md

Fix typo in keyboard shortcut for switching workspaces

Fix typo in difference-between-pop-ubuntu.md

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

Revert "Update deploy.yml"

---

content/system-firmware.md

Firmware updates that include EC firmware updates require a full power cycle to complete. Added a note suggesting either AC power unplug/plug or holding power button for 15 seconds.

add note for EC update

---

content/freezing-behavior.md

The existing explanation was for a previous version of the system.

Update the steps to generate a log file in freezing-behavior.md

---

content/pop-keyboard-shortcuts.md

This implements https://github.com/system76/docs/pull/1236 with the required improvements to the original PR.

Expand on workspace/display behavior for Pop!_OS GNOME keyboard shortcuts

---

content/codecs.md

Replaces https://github.com/system76/docs/pull/1141.

Codecs update

---

content/pop-shell.md

Common question in https://github.com/pop-os/shell from people following this support article, e.g. https://github.com/pop-os/shell/issues/1695#issuecomment-2359279518.

List Pop!_Shell branches for various Ubuntu versions

---

content/enable-hibernation.md

Closes https://github.com/system76/docs/issues/1269
depends on: https://github.com/system76/docs/pull/1278

Clarify hibernation disclaimer sentence
